#!/usr/bin/env ruby

require "redcub"

optparser = GetoptLong.new
optparser.set_options(['--pid-file', GetoptLong::REQUIRED_ARGUMENT],
		      ['--daemon', GetoptLong::NO_ARGUMENT])

deliver = RedCub::Deliver.new

optparser.each_option do |name, arg|
  case name
  when "--pid-file"
    deliver.pid_file = arg
  when "--daemon"
    deliver.daemon = true
  end
end

deliver.start
