#!/usr/bin/env ruby

require "redcub"

optparser = GetoptLong.new
optparser.set_options(['--pid-file', GetoptLong::REQUIRED_ARGUMENT],
		      ['--daemon', GetoptLong::NO_ARGUMENT])

sender = RedCub::Sender.new

optparser.each_option do |name, arg|
  case name
  when "--pid-file"
    sender.pid_file = arg
  when "--daemon"
    sender.daemon = true
  end
end

sender.start
